import {
  Call,
  Conditional,
  Scatter,
  Task,
  Workflow,
  ContextTypes,
  WdlEvent,
  WdlDocument,
  Project,
  InputParameter,
  OutputParameter,
  DeclarationParameter,
  print,
  PrimitiveTypes,
  CompoundTypes,
  isCall,
  isScatter,
  isAction,
  isExecutable,
  isScatterIterator,
  isWorkflow,
  isTask,
  isConditional,
  WdlVersion,
  WdlErrors,
  WdlErrorType,
} from './model';
import { VisualizerEvent } from './visual/types';
import Visualizer from './visual/visualizer';
import './pipeline.scss';

const VERSION = PACKAGE_VERSION;

const pipeline = {
  VERSION,
  Call,
  Conditional,
  Scatter,
  Task,
  Workflow,
  ContextTypes,
  WdlEvent,
  WdlDocument,
  Project,
  InputParameter,
  OutputParameter,
  DeclarationParameter,
  print,
  Visualizer,
  VisualizerEvent,
  PrimitiveTypes,
  CompoundTypes,
  isCall,
  isScatter,
  isAction,
  isExecutable,
  isScatterIterator,
  isWorkflow,
  isTask,
  isConditional,
  WdlVersion,
  WdlErrors,
  WdlErrorType,
};

export {
  VERSION,
  Call,
  Conditional,
  Scatter,
  Task,
  Workflow,
  ContextTypes,
  WdlEvent,
  WdlDocument,
  Project,
  InputParameter,
  OutputParameter,
  DeclarationParameter,
  print,
  Visualizer,
  VisualizerEvent,
  PrimitiveTypes,
  CompoundTypes,
  isCall,
  isScatter,
  isAction,
  isExecutable,
  isScatterIterator,
  isWorkflow,
  isTask,
  isConditional,
  WdlVersion,
  WdlErrors,
  WdlErrorType,
};

export default pipeline;
